# Generated by Django 4.2 on 2023-05-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('numeroAlimento', models.CharField(max_length=10)),
                ('descricaoAlimento', models.CharField(max_length=255)),
                ('umidade', models.CharField(max_length=20)),
                ('energiaKcal', models.CharField(max_length=20)),
                ('energiaKj', models.CharField(max_length=20)),
                ('proteina', models.CharField(max_length=20)),
                ('lipideos', models.CharField(max_length=20)),
                ('colesterol', models.CharField(max_length=20)),
                ('carboidrato', models.CharField(max_length=20)),
                ('fibraAlimentar', models.CharField(max_length=20)),
                ('cinzas', models.CharField(max_length=20)),
                ('calcio', models.CharField(max_length=20)),
                ('magnesio', models.CharField(max_length=20)),
                ('manganes', models.CharField(max_length=20)),
                ('fosforo', models.CharField(max_length=20)),
                ('ferro', models.CharField(max_length=20)),
                ('sodio', models.CharField(max_length=20)),
                ('potassio', models.CharField(max_length=20)),
                ('cobre', models.CharField(max_length=20)),
                ('zinco', models.CharField(max_length=20)),
                ('retinol', models.CharField(max_length=20)),
                ('re', models.CharField(max_length=20)),
                ('rae', models.CharField(max_length=20)),
                ('tiamina', models.CharField(max_length=20)),
                ('riboflavina', models.CharField(max_length=20)),
                ('piridoxina', models.CharField(max_length=20)),
                ('niacina', models.CharField(max_length=20)),
                ('vitaminaC', models.CharField(max_length=20)),
                ('created_at', models.CharField(max_length=30)),
                ('updated_at', models.CharField(max_length=30)),
            ],
        ),
    ]
