# Generated by Django 4.2 on 2023-05-01 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alimentos', '0002_alter_alimento_calcio_alter_alimento_carboidrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.CharField(choices=[('1', 'A PARTIR DAS 7:00 - CAFÉ DA MANHÃ'), ('2', 'DAS 10:00 ÀS 11:00 - LANCHE DA MANHÃ'), ('3', 'A PARTIR DAS 13:00 - ALMOÇO'), ('4', 'ENTRE 16:00 E 17:00 - LANCHE DA TARDE'), ('5', 'ATÉ ÀS 21:00 - JANTAR')], default='1', max_length=50)),
                ('created_at', models.CharField(max_length=30)),
                ('updated_at', models.CharField(max_length=30)),
                ('alimentos', models.ManyToManyField(to='alimentos.alimento', verbose_name='alimentos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
