# Generated by Django 4.2 on 2023-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0004_alter_refeicao_options_alter_refeicao_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
