# Generated by Django 4.2 on 2023-05-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0006_alter_refeicao_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='alimentos',
        ),
        migrations.CreateModel(
            name='Porcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('unidade_medida', models.CharField(default='g', max_length=100)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.refeicao')),
            ],
            options={
                'verbose_name_plural': 'Porções',
            },
        ),
    ]
